"""OnChainVerifier — turns an LLMHypothesis into on-chain evidence.

Pipeline:
  1. Parse IF clause → extract target address, condition keywords
  2. OnChainClient reads live state (block, balances, storage)
  3. If ETH_RPC_URL + forge available → generate Foundry harness + run
  4. If forge unavailable → LLM generates a structured PoC template
  5. Returns VerificationResult with all evidence attached

This is the bridge between "Pi said there's a bug" and "here is the
block-level proof that the precondition actually exists on-chain."

Usage:
    from core.on_chain_verifier import OnChainVerifier
    verifier = OnChainVerifier()
    result = verifier.verify(hypothesis, contract_address="0x...")
    print(result.verdict)        # STATE_VERIFIED | POC_PROVEN | UNVERIFIABLE
    print(result.evidence)       # on-chain state snapshot
    print(result.poc_code)       # Foundry test harness (if generated)
"""
from __future__ import annotations

import os
import re
import shutil
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from core.onchain_client import OnChainClient, RPCError


# ── Result dataclass ──────────────────────────────────────────────────────────

@dataclass
class VerificationResult:
    hypothesis_fragment: str
    verdict: str           # STATE_VERIFIED | POC_PROVEN | UNVERIFIABLE | FAIL
    reason: str            = ""
    evidence: dict         = field(default_factory=dict)
    poc_code: str          = ""
    poc_path: str          = ""
    block_number: int      = 0
    target_address: str    = ""
    balance_delta_eth: float = 0.0

    def to_gate_data(self) -> dict:
        """Convert to gate3_simulation_result format for VerificationLoop."""
        return {
            "balance_delta":      self.balance_delta_eth * 2000,  # rough ETH→USD
            "balance_delta_wei":  int(self.balance_delta_eth * 1e18),
            "verdict":            self.verdict,
            "reason":             self.reason,
            "evidence":           self.evidence,
            "poc_path":           self.poc_path,
            "block_number":       self.block_number,
            "target_address":     self.target_address,
        }


# ── Address + condition extraction ───────────────────────────────────────────

def _extract_address(text: str) -> str:
    """Pull first 0x... Ethereum address from text."""
    m = re.search(r"0x[0-9a-fA-F]{40}", text)
    return m.group(0) if m else ""


def _extract_conditions(hypothesis: str) -> dict:
    """
    Parse IF/THEN/BECAUSE clauses into structured conditions.
    Returns: {if_clause, then_clause, because_clause, keywords}
    """
    h = hypothesis.strip()
    patterns = {
        "if_clause":      r"IF\s+(.+?)\s+THEN",
        "then_clause":    r"THEN\s+(.+?)\s+BECAUSE",
        "because_clause": r"BECAUSE\s+(.+?)$",
    }
    result = {}
    for key, pat in patterns.items():
        m = re.search(pat, h, re.IGNORECASE | re.DOTALL)
        result[key] = m.group(1).strip() if m else ""

    # Extract vulnerability keywords for RPC state focus
    text_lower = hypothesis.lower()
    keywords = []
    for kw in ("overflow", "underflow", "reentrancy", "flash_loan", "oracle",
                "access_control", "drain", "liquidat", "shares", "totalassets",
                "totalborrowassets", "totalsupply"):
        if kw in text_lower:
            keywords.append(kw)
    result["keywords"] = keywords
    return result


# ── Foundry harness generator ─────────────────────────────────────────────────

_HARNESS_TEMPLATE = textwrap.dedent("""\
    // SPDX-License-Identifier: MIT
    // Auto-generated by Nexus Trinity OnChainVerifier
    // Hypothesis: {hypothesis_fragment}
    pragma solidity ^0.8.19;

    import "forge-std/Test.sol";
    import "forge-std/console.sol";

    interface ITarget {{
        // TODO: add interface methods for {contract_name}
    }}

    contract ExploitTest is Test {{
        // Target: {target_address} at block {block_number}
        address constant TARGET = {target_address};
        ITarget target;

        function setUp() public {{
            vm.createSelectFork(vm.envString("ETH_RPC_URL"), {block_number});
            target = ITarget(TARGET);
        }}

        function test_exploit() public {{
            uint256 balBefore = address(this).balance;

            // ── Reproduce IF condition ──────────────────────────────
            // Condition: {if_clause}
            // TODO: Set up the precondition state

            // ── Execute attack (THEN clause) ───────────────────────
            // Action: {then_clause}
            // TODO: Execute the attack sequence

            uint256 balAfter = address(this).balance;
            int256 delta = int256(balAfter) - int256(balBefore);
            console.log("balance_delta_wei:", delta);

            // Root cause: {because_clause}
            assertTrue(delta > 0, "exploit not profitable — check preconditions");
        }}

        // Receive ETH from target
        receive() external payable {{}}
    }}
""")


def _write_harness(
    contract_name: str,
    target_address: str,
    block_number: int,
    conditions: dict,
    hypothesis: str,
) -> tuple[str, str]:
    """Write a Foundry test harness. Returns (code, path)."""
    safe_name = re.sub(r"[^A-Za-z0-9]", "", contract_name or "Target")
    code = _HARNESS_TEMPLATE.format(
        hypothesis_fragment=hypothesis[:100],
        contract_name=safe_name,
        target_address=target_address or "address(0)",
        block_number=block_number,
        if_clause=conditions.get("if_clause", "?")[:80],
        then_clause=conditions.get("then_clause", "?")[:80],
        because_clause=conditions.get("because_clause", "?")[:120],
    )
    reports_dir = Path.home() / "AgentAI" / "reports" / "poc"
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / f"Exploit_{safe_name}.t.sol"
    path.write_text(code)
    return code, str(path)


# ── Main verifier ─────────────────────────────────────────────────────────────

class OnChainVerifier:
    """
    Verifies an LLMHypothesis against live chain state.

    Produces:
    - On-chain state snapshot (always, if ETH_RPC_URL set)
    - Foundry harness (always — humans need a starting point)
    - forge execution result (if forge is in PATH)
    """

    def __init__(self, rpc_url: str = "", router=None):
        self._client = OnChainClient(rpc_url=rpc_url)
        self._router = router

    @property
    def has_rpc(self) -> bool:
        return self._client.available

    @property
    def has_forge(self) -> bool:
        forge = shutil.which("forge") or os.path.expanduser("~/.foundry/bin/forge")
        return os.path.isfile(forge) if not shutil.which("forge") else True

    def verify(
        self,
        hypothesis: str,
        contract_address: str = "",
        contract_name: str = "",
        source_file: str = "",
    ) -> VerificationResult:
        """
        Main entry. Returns VerificationResult with all available evidence.

        Args:
            hypothesis:       Full IF/THEN/BECAUSE string
            contract_address: On-chain address (0x...). Auto-extracted from hypothesis if absent.
            contract_name:    Human name for the harness (e.g., "Morpho")
            source_file:      Path to .sol source (for harness context)
        """
        conditions = _extract_conditions(hypothesis)
        fragment   = hypothesis[:120]

        # Try to find target address
        target = (
            contract_address
            or _extract_address(hypothesis)
            or _extract_address(conditions.get("if_clause", ""))
        )
        name = contract_name or (Path(source_file).stem if source_file else "Target")

        # Step 1: Read on-chain state
        evidence: dict = {}
        block_number = 0

        if self.has_rpc and target:
            try:
                snap = self._client.validate_hypothesis_state(target, hypothesis)
                evidence = snap
                block_number = snap.get("block_number", 0)
                if snap.get("gate3_verdict") == "FAIL":
                    return VerificationResult(
                        hypothesis_fragment=fragment,
                        verdict="FAIL",
                        reason=snap.get("reason", "Contract not found on-chain"),
                        evidence=evidence,
                        target_address=target,
                    )
            except RPCError as e:
                evidence["rpc_error"] = str(e)
        elif self.has_rpc and not target:
            evidence["warning"] = "No on-chain address found in hypothesis — add 0x address for state reads"
        else:
            evidence["rpc"] = "ETH_RPC_URL not set — state read skipped"

        # Step 2: Always generate Foundry harness (needed for human review / forge run)
        poc_code, poc_path = _write_harness(
            contract_name=name,
            target_address=target or "0x0000000000000000000000000000000000000000",
            block_number=block_number or 0,
            conditions=conditions,
            hypothesis=hypothesis,
        )

        # Step 3: Run forge if available
        if self.has_forge and self.has_rpc and target and block_number:
            forge_result = self._run_forge(poc_path)
            if forge_result.get("success"):
                delta = forge_result.get("balance_delta_eth", 0.0)
                return VerificationResult(
                    hypothesis_fragment=fragment,
                    verdict="POC_PROVEN",
                    reason=f"forge test passed: balance_delta={delta:.4f} ETH",
                    evidence={**evidence, **forge_result},
                    poc_code=poc_code,
                    poc_path=poc_path,
                    block_number=block_number,
                    target_address=target,
                    balance_delta_eth=delta,
                )
            else:
                evidence["forge"] = forge_result

        # Step 4: Enrich harness with LLM if router available
        if self._router:
            enriched = self._llm_enrich_harness(hypothesis, conditions, poc_code)
            if enriched and enriched != poc_code:
                Path(poc_path).write_text(enriched)
                poc_code = enriched

        # No forge proof — but harness is ready and state is read
        verdict = "STATE_VERIFIED" if (self.has_rpc and target and not evidence.get("rpc_error")) else "UNVERIFIABLE"
        reason = (
            f"On-chain state read at block {block_number}. "
            f"Foundry harness written to {poc_path}. "
            f"Run: forge test --match-path {poc_path} --fork-url $ETH_RPC_URL -vvvv"
            if verdict == "STATE_VERIFIED"
            else "No ETH_RPC_URL or on-chain address — harness generated for manual execution"
        )

        return VerificationResult(
            hypothesis_fragment=fragment,
            verdict=verdict,
            reason=reason,
            evidence=evidence,
            poc_code=poc_code,
            poc_path=poc_path,
            block_number=block_number,
            target_address=target,
        )

    def _run_forge(self, test_path: str) -> dict:
        """Run forge test on the generated harness. Returns result dict."""
        import subprocess, json as _json
        forge = shutil.which("forge") or os.path.expanduser("~/.foundry/bin/forge")
        rpc = self._client._url
        try:
            proc = subprocess.run(
                [forge, "test", "--match-path", test_path,
                 "--fork-url", rpc, "-vvv", "--json"],
                capture_output=True, text=True, timeout=120,
                env={**os.environ, "ETH_RPC_URL": rpc},
            )
            delta = 0.0
            m = re.search(r"balance_delta_wei:\s*(-?\d+)", proc.stdout)
            if m:
                delta = int(m.group(1)) / 1e18
            return {
                "success":          proc.returncode == 0,
                "balance_delta_eth": delta,
                "stdout":           proc.stdout[:1000],
                "stderr":           proc.stderr[:300],
            }
        except subprocess.TimeoutExpired:
            return {"success": False, "error": "forge timed out after 120s"}
        except Exception as e:
            return {"success": False, "error": str(e)}

    def _llm_enrich_harness(self, hypothesis: str, conditions: dict, poc_code: str) -> str:
        """Ask LLM to fill in the TODO sections of the harness."""
        if not self._router:
            return poc_code
        system = (
            "You are a Foundry expert. You will be given a Solidity test harness with TODO "
            "comments and the vulnerability hypothesis it should test. Fill in ONLY the TODO "
            "sections with realistic Foundry test code. Preserve all existing code exactly. "
            "Output ONLY the complete filled-in Solidity file, no preamble."
        )
        prompt = (
            f"Hypothesis:\n{hypothesis}\n\n"
            f"IF clause: {conditions.get('if_clause', '')}\n"
            f"THEN clause: {conditions.get('then_clause', '')}\n\n"
            f"Harness to complete:\n```solidity\n{poc_code}\n```"
        )
        try:
            enriched = self._router.complete(prompt, system=system, gate=1)
            # Strip markdown fences if returned
            enriched = re.sub(r"^```solidity\s*", "", enriched.strip())
            enriched = re.sub(r"\s*```$", "", enriched)
            return enriched if "contract ExploitTest" in enriched else poc_code
        except Exception:
            return poc_code
